### ISSUE TITLE
How to specify Home directory in templatesDirectory?

### ISSUE THREAD

**Issue by Zyrsha** [cantonios/vscode-project-templates#1]
When configuring projectTemplates.templatesDirectory,

How can a home directory be specified?

`${env:HOME}` or use of any variables in the path causes the extension to stop working.

**Comment by cantonios** [comment]
They don't make this easy.  The predefined variables like `${env: ... }` are only resolved in `launch.json` and `tasks.json`.
- https://code.visualstudio.com/docs/editor/variables-reference

Most variables don't really make sense in this context, but I hacked together some code from VSCode's base to resolve them anyways.  

If you are able to pull from GitHub, do you want to try/test it before I release?

**Comment by cantonios** [comment]
Updated and released.  Should work now.
