### ISSUE TITLE
Provide templates from an extension

### ISSUE THREAD

**Issue by WebFreak001** [cantonios/vscode-project-templates#3]
I would like to contribute project templates from my extension (which can contain semi-variable content provided by the extension, like checking for dependency versions or by pulling entire git repositories), is there a contribution point in your extension which I could use already, or plans how you want to implement it?

**Comment by WebFreak001** [comment]
for reference this is my existing solution which I would like to make more flexible by moving it into another extension. Seeing that there is one already I thought of contributing instead of making my own:

https://github.com/Pure-D/code-d/wiki/Project-Creation
https://github.com/Pure-D/code-d/tree/master/templates
https://github.com/Pure-D/code-d/blob/master/src/project-creator.ts

**Comment by cantonios** [comment]
I want to keep this extension pretty simple.  You are free to fork and modify for yourself though.
