### ISSUE TITLE
Any plugin like this for Vim?

### ISSUE THREAD

**Issue by pianocomposer321** [cantonios/vscode-project-templates#6]
I had been using vscode for a while with the vscodevim extension, but have been trying to make the switch over to neovim instead. This plugin is _extremely_ useful, but I can't seem to find a plugin like it for vim/neovim. Does anyone know of a plugin like this?

**Comment by pianocomposer321** [comment]
Is there any chance of this plugin being ported to Vim?

**Comment by cantonios** [comment]
I'm not a vim user and I don't have the resources to do that.  Closing this.
